version: '3'
services:
  web:
    build: .
    container_name: crawler-web
    working_dir: /app
    environment:
      # 'db' to nazwa serwisu poniżej, docker/podman rozwiąże to jako hostname
      DATABASE_URL: "postgresql://postgres:tajnehaslo@db:5432/crawler_db?schema=public&connection_limit=20&pool_timeout=30"
      NODE_ENV: "production"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "rafal.gadomski@marafiki.pl"
      SMTP_PASS: "uvexgvvovwqvfxwp"
      SMTP_FROM_NAME: "SEO Crawler by Marafiki"
      SMTP_FROM_EMAIL: "info@marafiki.pl"
    ports:
      - "3555:3000" # Aplikacja dostępna na porcie 3555 hosta
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: crawler-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tajnehaslo
      POSTGRES_DB: crawler_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
